#!/usr/bin/env python3
"""Generate sat-vocab-flashcards.json — filters overly common words, tags part of speech."""
import json
import os
import re

# Words that are fine for SAT but too everyday / polysemous in general English — drop from deck.
COMMON_BLOCKLIST = {
    "acute", "advocate", "aggregate", "ambiguous", "anecdote", "apathy", "arbitrary", "articulate",
    "authentic", "bias", "candid", "cardinal", "catalyst", "coherent", "complacent", "consensus",
    "conjecture", "dilemma", "diligent", "discrete", "eminent", "explicit", "foster", "hamper",
    "implicit", "integral", "mandate", "mediocre", "objective", "obsolete", "paradox", "plausible",
    "pragmatic", "precedent", "profound", "resilient", "rhetoric", "sanction", "sparse", "subtle",
    "viable", "volatile", "wane", "zenith", "notorious", "novice", "mundane", "naive", "jargon",
    "derivative", "inhibit", "mitigate", "pristine", "reconcile", "cultivate", "foster",
    "consensus", "elevate", "leverage", "rash", "kindle", "revere", "scrutinize", "skeptic",
}

# Extra challenging replacements (word, definition, part_of_speech)
REPLACEMENTS = [
    ("abrogate", "repeal or do away with formally", "verb"),
    ("abscond", "leave hurriedly and secretly to escape custody", "verb"),
    ("abstruse", "difficult to understand; obscure", "adj"),
    ("accretion", "growth or increase by gradual addition", "noun"),
    ("acerbic", "sharp and forthright; harsh in tone", "adj"),
    ("acumen", "keen insight and good judgment", "noun"),
    ("adamant", "refusing to change one’s mind", "adj"),
    ("admonitory", "giving a firm warning or reprimand", "adj"),
    ("adventitious", "coming from outside; not inherent", "adj"),
    ("adumbrate", "outline faintly; foreshadow", "verb"),
    ("anathema", "something intensely disliked; a curse", "noun"),
    ("approbation", "approval or praise", "noun"),
    ("arrogate", "claim or seize without justification", "verb"),
    ("assiduous", "showing great care and perseverance", "adj"),
    ("attenuate", "reduce in force, effect, or value", "verb"),
    ("bowdlerize", "remove material considered improper", "verb"),
    ("burnish", "polish; enhance a reputation", "verb"),
    ("cadge", "ask for or obtain something scrounging", "verb"),
    ("calumniate", "make false and defamatory statements about", "verb"),
    ("contumacious", "stubbornly disobedient", "adj"),
    ("denigrate", "criticize unfairly; disparage", "verb"),
    ("deprecate", "express disapproval of; belittle", "verb"),
    ("desiccate", "remove all moisture; dry out", "verb"),
    ("dilettante", "a person with superficial interest in an art", "noun"),
    ("effrontery", "insolent boldness; audacity", "noun"),
    ("encomium", "a speech or text of high praise", "noun"),
    ("eschew", "deliberately avoid; shun", "verb"),
    ("exigent", "pressing; demanding immediate action", "adj"),
    ("expurgate", "remove objectionable material from a text", "verb"),
    ("gainsay", "deny or contradict", "verb"),
    ("heterodox", "not conforming with accepted standards", "adj"),
    ("imbroglio", "a complicated and confused situation", "noun"),
    ("impugn", "dispute the truth or validity of", "verb"),
    ("inchoate", "just begun and not fully formed", "adj"),
    ("inimical", "tending to obstruct or harm; unfriendly", "adj"),
    ("insuperable", "impossible to overcome", "adj"),
    ("interloper", "a person who intrudes where unwelcome", "noun"),
    ("intransigent", "unwilling to change one’s views", "adj"),
    ("importune", "harass with persistent requests", "verb"),
    ("limpid", "clear; transparent; easily understood", "adj"),
    ("obloquy", "strong public criticism; disgrace", "noun"),
    ("odium", "widespread hatred or disgust", "noun"),
    ("opprobrium", "harsh criticism or censure", "noun"),
    ("ossify", "harden; become rigid in habits or ideas", "verb"),
    ("palliate", "make a problem seem less serious", "verb"),
    ("panacea", "a remedy for all difficulties", "noun"),
    ("peccadillo", "a small, relatively unimportant offense", "noun"),
    ("perspicacious", "having keen mental perception", "adj"),
    ("phlegmatic", "calm and unemotional in temperament", "adj"),
    ("salubrious", "health-giving; favorable to well-being", "adj"),
    ("sedulous", "showing dedication and diligence", "adj"),
    ("soporific", "tending to induce drowsiness", "adj"),
    ("subterfuge", "deceit used to achieve a goal", "noun"),
    ("tendentious", "expressing a partisan viewpoint", "adj"),
    ("venality", "susceptibility to bribery; corruption", "noun"),
    ("verisimilitude", "appearance of being true or real", "noun"),
    ("vituperate", "blame or insult in strong language", "verb"),
]

WORDS_RAW = [
    ("abate", "become less intense or severe"),
    ("aberration", "a departure from what is normal or expected"),
    ("abhor", "regard with disgust or hatred"),
    ("abstain", "restrain from doing something"),
    ("acclaim", "praise enthusiastically"),
    ("acquiesce", "accept reluctantly but without protest"),
    ("acrimony", "bitterness or ill feeling"),
    ("admonish", "warn firmly; scold mildly"),
    ("adroit", "clever and skillful"),
    ("adversary", "an opponent in a conflict"),
    ("aesthetic", "concerned with beauty or artistic taste"),
    ("affable", "friendly and easy to talk to"),
    ("affluent", "wealthy; abundant"),
    ("aggrandize", "increase power, status, or wealth"),
    ("alacrity", "cheerful readiness or promptness"),
    ("alleviate", "make suffering or a problem less severe"),
    ("aloof", "distant or detached in manner"),
    ("altruistic", "selflessly concerned for others"),
    ("ambivalent", "having mixed feelings"),
    ("ameliorate", "make something bad better"),
    ("amiable", "friendly and pleasant"),
    ("anachronism", "a thing belonging to another time period"),
    ("analogous", "comparable in certain respects"),
    ("anarchy", "absence of government or order"),
    ("animosity", "strong hostility"),
    ("antipathy", "a deep-seated feeling of dislike"),
    ("antithesis", "a direct opposite; a contrast"),
    ("apathetic", "showing little interest or concern"),
    ("archaic", "very old or old-fashioned"),
    ("ascetic", "severe self-discipline; avoiding pleasure"),
    ("assuage", "make an unpleasant feeling less intense"),
    ("atrophy", "waste away from disuse"),
    ("austere", "severe in manner; without comfort"),
    ("authoritarian", "favoring strict obedience to authority"),
    ("autonomous", "self-governing; independent"),
    ("aversion", "a strong dislike"),
    ("banal", "lacking originality; clichéd"),
    ("belie", "fail to give a true impression of"),
    ("belligerent", "hostile and aggressive"),
    ("benevolent", "well-meaning and kindly"),
    ("bolster", "support or strengthen"),
    ("boorish", "rough and bad-mannered"),
    ("burgeon", "grow or increase rapidly"),
    ("cacophony", "a harsh mixture of sounds"),
    ("callous", "showing no sympathy"),
    ("calumny", "a false statement meant to harm reputation"),
    ("candor", "the quality of being open and honest"),
    ("capricious", "given to sudden changes of mood"),
    ("captivate", "attract and hold interest"),
    ("castigate", "reprimand severely"),
    ("caustic", "sarcastic in a biting way"),
    ("censor", "suppress unacceptable parts"),
    ("censure", "express severe disapproval"),
    ("cerebral", "intellectual rather than emotional"),
    ("circumspect", "wary and unwilling to take risks"),
    ("clandestine", "kept secret"),
    ("coalesce", "come together to form one mass"),
    ("cogent", "clear, logical, and convincing"),
    ("compliant", "disposed to agree or obey"),
    ("conciliatory", "intended to placate or reconcile"),
    ("condone", "accept behavior one disapproves of"),
    ("conspicuous", "easily seen; attracting notice"),
    ("contentious", "likely to cause disagreement"),
    ("contrite", "feeling remorse"),
    ("conundrum", "a confusing problem"),
    ("converge", "come together from different directions"),
    ("convoluted", "extremely complex and difficult to follow"),
    ("copious", "abundant in quantity"),
    ("corroborate", "confirm or support with evidence"),
    ("credulous", "too ready to believe"),
    ("culpable", "deserving blame"),
    ("cursory", "hasty and not thorough"),
    ("curtail", "reduce in extent or quantity"),
    ("dearth", "a scarcity or lack"),
    ("debunk", "expose the falseness of"),
    ("decorum", "behavior in keeping with good taste"),
    ("deference", "humble respect for another’s judgment"),
    ("deflect", "cause to change direction; turn aside"),
    ("delineate", "describe precisely"),
    ("denounce", "publicly declare wrong or evil"),
    ("deplete", "use up resources"),
    ("despot", "a ruler with total power"),
    ("deteriorate", "become progressively worse"),
    ("detrimental", "harmful"),
    ("didactic", "intended to teach, often moralizing"),
    ("diffident", "modest or shy due to lack of confidence"),
    ("discern", "perceive or recognize clearly"),
    ("discrepancy", "a lack of compatibility between facts"),
    ("disdain", "the feeling that someone is unworthy"),
    ("disinterested", "unbiased; not influenced by personal gain"),
    ("disparage", "regard as worthless; belittle"),
    ("disparate", "essentially different"),
    ("disseminate", "spread widely"),
    ("dissonance", "lack of harmony; tension"),
    ("dogmatic", "asserting opinions as established truth"),
    ("dubious", "hesitating or doubting; questionable"),
    ("duplicity", "deceitfulness; double-dealing"),
    ("ebullient", "cheerful and full of energy"),
    ("eccentric", "unconventional and slightly strange"),
    ("eclectic", "deriving ideas from a broad range"),
    ("elicit", "evoke or draw out a response"),
    ("eloquent", "fluent and persuasive in speaking"),
    ("elucidate", "make clear; explain"),
    ("embellish", "make more attractive by adding detail"),
    ("empirical", "based on observation or experience"),
    ("enervate", "drain of energy or vitality"),
    ("engender", "cause or give rise to"),
    ("enigma", "a person or thing that is mysterious"),
    ("ephemeral", "lasting for a very short time"),
    ("equanimity", "calm composure under stress"),
    ("equivocate", "use ambiguous language to mislead"),
    ("eradicate", "destroy completely"),
    ("erratic", "unpredictably uneven"),
    ("erudite", "showing great learning"),
    ("esoteric", "intended for a small informed group"),
    ("eulogy", "a speech praising someone who has died"),
    ("euphemism", "a mild word substituted for a harsh one"),
    ("exacerbate", "make a problem worse"),
    ("exacting", "demanding great skill or care"),
    ("exonerate", "absolve from blame"),
    ("expedient", "convenient though possibly improper"),
    ("extraneous", "irrelevant; not belonging"),
    ("facile", "ignoring the true complexities; too easy"),
    ("fastidious", "very attentive to accuracy and detail"),
    ("fatuous", "foolish and complacent"),
    ("fervent", "having great intensity of feeling"),
    ("flippant", "not showing serious respect"),
    ("flout", "openly disregard a rule"),
    ("foment", "instigate trouble"),
    ("forestall", "prevent by acting ahead"),
    ("fortitude", "courage in pain or adversity"),
    ("fractious", "irritable and quarrelsome"),
    ("frivolous", "not serious; carefree to excess"),
    ("frugal", "sparing or economical with money"),
    ("futile", "incapable of producing a result"),
    ("garrulous", "excessively talkative"),
    ("germane", "relevant to the subject"),
    ("glib", "fluent but insincere or shallow"),
    ("gregarious", "fond of company; sociable"),
    ("guile", "sly or cunning intelligence"),
    ("hackneyed", "lacking originality through overuse"),
    ("hardy", "robust; able to endure difficult conditions"),
    ("hedonist", "a person devoted to pleasure"),
    ("hegemony", "leadership or dominance of one group"),
    ("hyperbole", "exaggerated statements not meant literally"),
    ("iconoclast", "a person who attacks cherished beliefs"),
    ("ignominious", "deserving or causing public disgrace"),
    ("illicit", "forbidden by law or rules"),
    ("immutable", "unchanging over time"),
    ("impartial", "treating all rivals equally; fair"),
    ("impede", "delay or prevent progress"),
    ("imperious", "domineering; arrogant"),
    ("impertinent", "not showing respect; irrelevant"),
    ("impetuous", "acting suddenly with little thought"),
    ("imprudent", "not showing care for consequences"),
    ("inadvertent", "not resulting from intention"),
    ("incisive", "clear and sharply analytical"),
    ("incongruous", "not in harmony with surroundings"),
    ("incorrigible", "unable to be corrected or reformed"),
    ("indifferent", "having no preference; mediocre"),
    ("indigenous", "originating naturally in a place"),
    ("indignant", "feeling anger at unfair treatment"),
    ("indolent", "lazy; wanting to avoid activity"),
    ("inept", "having no skill; inappropriate"),
    ("inexorable", "impossible to stop or persuade"),
    ("ingenious", "clever and original"),
    ("ingenuous", "innocent and unsuspecting"),
    ("innocuous", "not harmful or offensive"),
    ("inscrutable", "impossible to understand"),
    ("insipid", "lacking flavor or interest"),
    ("insolent", "rude and disrespectful"),
    ("intermittent", "stopping and starting at intervals"),
    ("intrepid", "fearless; adventurous"),
    ("inundate", "overwhelm with things to deal with"),
    ("invective", "insulting or abusive language"),
    ("invigorate", "give strength or energy to"),
    ("irascible", "easily angered"),
    ("jubilant", "feeling great joy"),
    ("judicious", "showing good judgment"),
    ("laconic", "using very few words"),
    ("laudable", "deserving praise"),
    ("lavish", "sumptuously rich or elaborate"),
    ("lethargic", "affected by sluggishness"),
    ("levity", "treatment of a serious matter with humor"),
    ("loquacious", "tending to talk a great deal"),
    ("lucid", "clearly expressed; bright"),
    ("ludicrous", "so foolish it provokes laughter"),
    ("magnanimous", "generous in forgiving"),
    ("maladroit", "ineffective; clumsy"),
    ("malevolent", "wishing evil on others"),
    ("malign", "speak harmful untruths about"),
    ("malleable", "easily influenced; able to be hammered"),
    ("melancholy", "a feeling of pensive sadness"),
    ("mercurial", "subject to sudden changes of mood"),
    ("meticulous", "showing great attention to detail"),
    ("modicum", "a small quantity"),
    ("mollify", "calm the anger of"),
    ("monotonous", "dull and tedious"),
    ("morose", "sullen and ill-humored"),
    ("myopic", "lacking imagination or foresight"),
    ("nascent", "just coming into existence"),
    ("nebulous", "vague or ill-defined"),
    ("nefarious", "wicked or criminal"),
    ("negligible", "so small as to be unimportant"),
    ("nonchalant", "casually calm and relaxed"),
    ("noxious", "harmful or poisonous"),
    ("nuance", "a subtle difference"),
    ("obdurate", "stubbornly refusing to change"),
    ("obfuscate", "make obscure or unclear"),
    ("oblivious", "unaware of what is happening"),
    ("obsequious", "obedient to an excessive degree"),
    ("obstinate", "stubbornly refusing to change"),
    ("ominous", "giving the impression something bad will happen"),
    ("onerous", "involving great effort and difficulty"),
    ("opaque", "not able to be seen through; hard to understand"),
    ("opportune", "well chosen for a particular time"),
    ("ostentatious", "designed to impress or attract notice"),
    ("painstaking", "done with great care and thoroughness"),
    ("parsimony", "extreme unwillingness to spend"),
    ("partisan", "a strong supporter of a party"),
    ("pathos", "a quality evoking pity or sadness"),
    ("paucity", "a small number of something"),
    ("pedantic", "excessively concerned with minor rules"),
    ("pejorative", "expressing disapproval"),
    ("penchant", "a strong liking"),
    ("perceptive", "having sensitive insight"),
    ("perfunctory", "carried out with minimum effort"),
    ("permeate", "spread throughout"),
    ("pernicious", "having a harmful effect in a gradual way"),
    ("petulant", "childishly sulky or bad-tempered"),
    ("philanthropic", "seeking to promote human welfare"),
    ("plethora", "a large excess of something"),
    ("poignant", "evoking sadness or regret"),
    ("polemic", "a strong verbal attack"),
    ("precarious", "not securely held; uncertain"),
    ("precipitate", "cause to happen suddenly; hasty"),
    ("preclude", "prevent from happening"),
    ("predilection", "a preference for something"),
    ("prerequisite", "required beforehand"),
    ("presumptuous", "failing to observe limits of due respect"),
    ("probity", "integrity and honesty"),
    ("proclivity", "a tendency to choose or do something"),
    ("profuse", "very plentiful; extravagant"),
    ("proliferate", "increase rapidly in number"),
    ("prosaic", "lacking poetic beauty; dull"),
    ("provincial", "narrow in outlook; of a province"),
    ("prudent", "acting with care for the future"),
    ("pugnacious", "eager to fight"),
    ("quandary", "a state of uncertainty in a dilemma"),
    ("quell", "subdue or put an end to"),
    ("querulous", "complaining in a petulant way"),
    ("rancor", "bitterness or resentfulness"),
    ("rebuke", "express sharp disapproval"),
    ("recalcitrant", "stubbornly uncooperative"),
    ("recluse", "a person who lives in isolation"),
    ("recondite", "little known; abstruse"),
    ("refute", "prove a statement false"),
    ("relegate", "assign to a lower position"),
    ("relinquish", "voluntarily cease to keep"),
    ("remiss", "lacking care for duty"),
    ("renounce", "formally give up"),
    ("reprehensible", "deserving censure"),
    ("reproach", "address in a way expressing disapproval"),
    ("repudiate", "refuse to accept"),
    ("rescind", "revoke or cancel officially"),
    ("resolute", "admirably purposeful"),
    ("rudimentary", "involving basic principles; undeveloped"),
    ("sacrosanct", "regarded as too important to interfere with"),
    ("sagacious", "having keen judgment"),
    ("salient", "most noticeable or important"),
    ("sanguine", "optimistic, especially in difficulty"),
    ("sardonic", "grimly mocking"),
    ("scathing", "witheringly harsh"),
    ("scrupulous", "diligent and thorough"),
    ("solicitous", "showing anxious care"),
    ("specious", "superficially plausible but wrong"),
    ("spurious", "not genuine; false"),
    ("stagnant", "not flowing; showing no activity"),
    ("steadfast", "resolutely unwavering"),
    ("stigma", "a mark of disgrace"),
    ("stoic", "enduring pain without complaint"),
    ("stringent", "strict and precise"),
    ("subjugate", "bring under domination"),
    ("sublime", "of great excellence or beauty"),
    ("substantiate", "provide evidence to support"),
    ("succinct", "briefly and clearly expressed"),
    ("superfluous", "unnecessary, especially through excess"),
    ("suppress", "forcibly put an end to"),
    ("surreptitious", "kept secret because improper"),
    ("tacit", "understood without being stated"),
    ("taciturn", "reserved or uncommunicative"),
    ("tantamount", "equivalent in seriousness"),
    ("tedious", "too long or dull"),
    ("temerity", "excessive confidence or boldness"),
    ("tenacious", "tending to keep a firm hold"),
    ("terse", "sparing in words"),
    ("tirade", "a long angry speech"),
    ("torpor", "a state of physical or mental inactivity"),
    ("trenchant", "vigorous in expression"),
    ("trepidation", "great worry about something"),
    ("trite", "overused and consequently boring"),
    ("truculent", "eager to argue or fight"),
    ("ubiquitous", "present everywhere"),
    ("unassailable", "unable to be attacked or questioned"),
    ("uncanny", "strange or mysterious"),
    ("undermine", "erode the base of; weaken"),
    ("unequivocal", "leaving no doubt"),
    ("unprecedented", "never done or known before"),
    ("usurp", "take a position of power illegally"),
    ("vacillate", "alternate between opinions"),
    ("vacuous", "having no intelligence or interest"),
    ("venerate", "regard with great respect"),
    ("verbose", "using more words than needed"),
    ("vex", "annoy or worry"),
    ("vilify", "speak or write about in abusive terms"),
    ("vindicate", "clear of blame or suspicion"),
    ("virulent", "bitterly hostile; severe"),
    ("vociferous", "loud and insistent"),
    ("voracious", "wanting great quantities of food or knowledge"),
    ("whimsical", "playfully quaint or fanciful"),
    ("wily", "skilled at gaining an advantage"),
    ("zealous", "showing great fervor for a person or cause"),
]

NOUN_SUFFIX = (
    "tion", "sion", "ness", "ment", "ity", "ism", "ist", "ance", "ence", "archy", "cracy",
    "logue", "hood", "ship", "dom", "age", "ure", "eur",
)
ADJ_SUFFIX = ("ous", "ive", "ble", "ial", "ent", "ant", "ic", "ful", "less", "ary", "ory", "ile", "ine", "ate")  # -ate often verb — refined below
ADV_EXCEPT = {"family", "supply", "ugly", "silly", "holly", "jolly", "belly"}

POS_MANUAL = {
    "aggregate": "noun",
    "articulate": "verb",
    "commensurate": "adj",
    "delegate": "verb",
    "duplicate": "verb",
    "moderate": "adj",
    "precipitate": "verb",
    "separate": "verb",
    "advocate": "verb",
    "attribute": "verb",
    "complement": "noun",
    "compound": "noun",
    "conflict": "noun",
    "digest": "verb",
    "incense": "verb",
    "intimate": "adj",
    "resent": "verb",
    "subject": "noun",
    "abstract": "adj",
    "august": "adj",
    "bent": "noun",
    "buffet": "verb",
    "compact": "adj",
    "concert": "verb",
    "console": "verb",
    "desert": "verb",
    "digest": "noun",
    "essay": "verb",
    "excuse": "verb",
    "exploit": "verb",
    "foment": "verb",
    "garner": "verb",
    "grovel": "verb",
    "impact": "noun",
    "implore": "verb",
    "infer": "verb",
    "malign": "verb",
    "oblique": "adj",
    "pedestrian": "adj",
    "permit": "verb",
    "project": "verb",
    "rebuke": "verb",
    "refuse": "verb",
    "reject": "verb",
    "second": "verb",
    "subject": "verb",
    "suspect": "verb",
    "syndicate": "verb",
    "undermine": "verb",
    "upbraid": "verb",
    "wheedle": "verb",
    "abrogate": "verb",
    "abscond": "verb",
    "adumbrate": "verb",
    "arrogate": "verb",
    "attenuate": "verb",
    "bowdlerize": "verb",
    "burnish": "verb",
    "cadge": "verb",
    "calumniate": "verb",
    "denigrate": "verb",
    "deprecate": "verb",
    "desiccate": "verb",
    "eschew": "verb",
    "expurgate": "verb",
    "gainsay": "verb",
    "impugn": "verb",
    "importune": "verb",
    "ossify": "verb",
    "palliate": "verb",
    "vituperate": "verb",
    "melancholy": "noun",
    "parsimony": "noun",
    "pathos": "noun",
    "paucity": "noun",
    "penchant": "noun",
    "rancor": "noun",
    "zenith": "noun",
    "acumen": "noun",
    "anathema": "noun",
    "approbation": "noun",
    "dilettante": "noun",
    "effrontery": "noun",
    "encomium": "noun",
    "imbroglio": "noun",
    "interloper": "noun",
    "obloquy": "noun",
    "odium": "noun",
    "opprobrium": "noun",
    "panacea": "noun",
    "peccadillo": "noun",
    "subterfuge": "noun",
    "venality": "noun",
    "verisimilitude": "noun",
    "accretion": "noun",
    "hedonist": "noun",
    "iconoclast": "noun",
    "partisan": "noun",
    "recluse": "noun",
    "skeptic": "noun",
    "stigma": "noun",
    "hyperbole": "noun",
    "eulogy": "noun",
    "euphemism": "noun",
    "guile": "noun",
    "hegemony": "noun",
    "cacophony": "noun",
    "dissonance": "noun",
    "conundrum": "noun",
    "dearth": "noun",
    "despot": "noun",
    "enigma": "noun",
    "equanimity": "noun",
    "fortitude": "noun",
    "jargon": "noun",
    "levity": "noun",
    "modicum": "noun",
    "nuance": "noun",
    "paradigm": "noun",
    "polemic": "noun",
    "probity": "noun",
    "proclivity": "noun",
    "quandary": "noun",
    "tirade": "noun",
    "torpor": "noun",
    "trepidation": "noun",
    "mandate": "noun",
    "catalyst": "noun",
}


def classify_pos(word: str) -> str:
    w = word.lower()
    if w in POS_MANUAL:
        return POS_MANUAL[w]
    if w.endswith("ly") and len(w) > 4 and w not in ADV_EXCEPT:
        return "adverb"
    for suf in NOUN_SUFFIX:
        if w.endswith(suf):
            return "noun"
    if w.endswith("ous") or w.endswith("ive") or (w.endswith("ent") and not w.endswith("ment")) or w.endswith("ant"):
        if w.endswith("ment"):
            pass
        else:
            return "adj"
    for suf in ("able", "ible", "ary", "ory", "ful", "less", "ial", "ic"):
        if w.endswith(suf):
            return "adj"
    if w.endswith("ish") or w.endswith("ive"):
        return "adj"
    if w.endswith("ize") or w.endswith("ise") or w.endswith("ify"):
        return "verb"
    if w.endswith("en") and len(w) > 4 and w not in {"often", "given", "women", "children"}:
        return "verb"
    if w.endswith("ate") and len(w) > 5:
        return "verb"
    if re.search(r"(ify|ize|ise)$", w):
        return "verb"
    # gerund-style nouns
    if w.endswith("ing") and len(w) > 5:
        return "other"
    return "other"


ROOTS = [
    ("anthrop", "human", "Greek", ["anthropology", "philanthropy", "misanthrope"]),
    ("bio", "life", "Greek", ["biology", "symbiosis", "antibiotic"]),
    ("chron", "time", "Greek", ["chronology", "anachronism", "chronic"]),
    ("cosm", "world, universe", "Greek", ["cosmos", "cosmetic", "microcosm"]),
    ("dem", "people", "Greek", ["democracy", "demographics", "epidemic"]),
    ("dyn", "power", "Greek", ["dynasty", "dynamic", "dynamite"]),
    ("gen", "birth, race, kind", "Greek/Latin", ["generate", "genesis", "genetic", "benign"]),
    ("geo", "earth", "Greek", ["geology", "geography", "geometry"]),
    ("graph", "write", "Greek", ["graphic", "biography", "photograph"]),
    ("log", "word, reason, study", "Greek", ["logic", "biology", "dialogue"]),
    ("meter", "measure", "Greek", ["thermometer", "diameter", "symmetry"]),
    ("morph", "form", "Greek", ["amorphous", "metamorphosis", "anthropomorphic"]),
    ("path", "feeling, suffering", "Greek", ["sympathy", "apathy", "pathology"]),
    ("phon", "sound", "Greek", ["phonics", "symphony", "cacophony"]),
    ("photo", "light", "Greek", ["photograph", "photosynthesis"]),
    ("psych", "mind", "Greek", ["psychology", "psychiatry"]),
    ("scope", "see, watch", "Greek", ["microscope", "telescope", "periscope"]),
    ("tele", "far", "Greek", ["telephone", "television", "telepathy"]),
    ("the", "god", "Greek", ["theology", "atheist", "monotheism"]),
    ("therm", "heat", "Greek", ["thermal", "thermometer", "hypothermia"]),
    ("act", "do, drive", "Latin", ["action", "react", "transact"]),
    ("aud", "hear", "Latin", ["audience", "audible", "audit"]),
    ("bell", "war", "Latin", ["belligerent", "rebel", "antebellum"]),
    ("bene", "good, well", "Latin", ["benefit", "benevolent", "benign"]),
    ("bon", "good", "Latin", ["bonus", "bona fide"]),
    ("cap", "take, hold", "Latin", ["capture", "capacity", "incipient"]),
    ("ced", "go, yield", "Latin", ["precede", "recede", "concession"]),
    ("cent", "hundred", "Latin", ["century", "percent", "bicentennial"]),
    ("circum", "around", "Latin", ["circumference", "circumnavigate", "circumspect"]),
    ("cis", "cut", "Latin", ["incision", "precise", "scissors"]),
    ("cogn", "know", "Latin", ["recognize", "incognito", "cognition"]),
    ("corp", "body", "Latin", ["corporate", "corpse", "incorporate"]),
    ("cred", "believe, trust", "Latin", ["credible", "credulous", "credential"]),
    ("culp", "blame", "Latin", ["culpable", "exculpate", "culprit"]),
    ("cur", "run, care", "Latin", ["current", "concur", "curator"]),
    ("dict", "say", "Latin", ["predict", "contradict", "verdict"]),
    ("doc", "teach", "Latin", ["doctor", "doctrine", "indoctrinate"]),
    ("dom", "rule, home", "Latin", ["dominate", "domestic", "predominant"]),
    ("duc", "lead", "Latin", ["conduct", "deduce", "seduce"]),
    ("equ", "equal", "Latin", ["equity", "equanimity", "equivocate"]),
    ("fac", "make, do", "Latin", ["factory", "benefactor", "facile"]),
    ("fer", "carry, bear", "Latin", ["transfer", "refer", "proliferate"]),
    ("fid", "faith, trust", "Latin", ["confide", "diffident", "perfidy"]),
    ("fin", "end, limit", "Latin", ["final", "define", "infinite"]),
    ("fort", "strong", "Latin", ["fortitude", "fortify", "fortress"]),
    ("frag", "break", "Latin", ["fragment", "refract", "fracture"]),
    ("fus", "pour", "Latin", ["confuse", "diffuse", "profuse"]),
    ("grad", "step, go", "Latin", ["progress", "degrade", "gradual"]),
    ("greg", "flock, herd", "Latin", ["congregate", "gregarious", "segregate"]),
    ("ject", "throw", "Latin", ["reject", "project", "conjecture"]),
    ("jud", "judge", "Latin", ["judicial", "prejudice", "adjudicate"]),
    ("junct", "join", "Latin", ["junction", "conjunction", "adjunct"]),
    ("jur", "swear, law", "Latin", ["jury", "perjury", "abjure"]),
    ("leg", "law, read", "Latin", ["legal", "privilege", "legacy"]),
    ("lev", "lift, light", "Latin", ["elevate", "levity", "alleviate"]),
    ("liber", "free", "Latin", ["liberty", "liberal", "deliver"]),
    ("loc", "place", "Latin", ["local", "relocate", "dislocate"]),
    ("loqu", "speak", "Latin", ["eloquent", "loquacious", "colloquial"]),
    ("luc", "light", "Latin", ["lucid", "elucidate", "translucent"]),
    ("magn", "great", "Latin", ["magnify", "magnitude", "magnanimous"]),
    ("mal", "bad", "Latin", ["malice", "malevolent", "maladroit"]),
    ("man", "hand", "Latin", ["manual", "manuscript", "emancipate"]),
    ("mem", "mind, memory", "Latin", ["memory", "memorialize", "commemorate"]),
    ("mit", "send", "Latin", ["transmit", "submit", "emit"]),
    ("mob", "move", "Latin", ["mobile", "motivate", "automobile"]),
    ("mort", "death", "Latin", ["mortal", "mortify", "rigor mortis"]),
    ("mut", "change", "Latin", ["mutation", "transmute", "commute"]),
    ("nom", "name", "Latin", ["nominate", "misnomer", "ignominious"]),
    ("nov", "new", "Latin", ["novelty", "innovate", "renovate"]),
    ("oper", "work", "Latin", ["operate", "cooperate", "opulent"]),
    ("pac", "peace", "Latin", ["pacify", "pacific"]),
    ("pass", "feel, suffer", "Latin", ["passion", "impassive", "compassion"]),
    ("ped", "foot (Latin); child (Greek)", "Latin/Greek", ["pedal", "pedestrian", "encyclopedia"]),
    ("pel", "drive, push", "Latin", ["compel", "expel", "propeller"]),
    ("pend", "hang", "Latin", ["depend", "pending", "appendix"]),
    ("pet", "seek", "Latin", ["compete", "impetus", "petition"]),
    ("phil", "love", "Greek", ["philosophy", "bibliophile"]),
    ("plic", "fold", "Latin", ["implicate", "replicate", "complicit"]),
    ("pon", "place, put", "Latin", ["component", "postpone", "opponent"]),
    ("port", "carry", "Latin", ["export", "import", "portable"]),
    ("pos", "place, put", "Latin", ["position", "compose", "deposit"]),
    ("prim", "first", "Latin", ["primary", "primitive", "primer"]),
    ("pug", "fight", "Latin", ["pugnacious", "impugn", "repugnant"]),
    ("reg", "rule, straight", "Latin", ["regulate", "regime", "derange"]),
    ("rupt", "break", "Latin", ["disrupt", "abrupt", "corrupt"]),
    ("sci", "know", "Latin", ["science", "conscience", "omniscient"]),
    ("scrib", "write", "Latin", ["describe", "inscribe", "proscribe"]),
    ("sec", "follow", "Latin", ["second", "sequential"]),
    ("sed", "sit", "Latin", ["sedentary", "preside", "residue"]),
    ("sens", "feel", "Latin", ["sensitive", "consensus", "resent"]),
    ("serv", "keep, save", "Latin", ["conserve", "preserve", "observe"]),
    ("spec", "look", "Latin", ["spectator", "circumspect", "introspection"]),
    ("spir", "breathe", "Latin", ["inspire", "conspire", "respiration"]),
    ("sta", "stand", "Latin", ["static", "obstacle", "status"]),
    ("stru", "build", "Latin", ["construct", "destroy", "instrument"]),
    ("tang", "touch", "Latin", ["tangible", "tangent", "contingent"]),
    ("temp", "time", "Latin", ["temporary", "contemporary", "extemporaneous"]),
    ("ten", "hold", "Latin", ["tenant", "tenacious", "retention"]),
    ("terr", "earth, land", "Latin", ["terrain", "territory", "extraterrestrial"]),
    ("tract", "pull", "Latin", ["attract", "contract", "tractable"]),
    ("trans", "across", "Latin", ["transfer", "transient", "transcend"]),
    ("uni", "one", "Latin", ["unify", "unanimous", "unilateral"]),
    ("vac", "empty", "Latin", ["vacate", "evacuate", "vacuous"]),
    ("vad", "go", "Latin", ["invade", "evade", "pervade"]),
    ("val", "worth, strength", "Latin", ["value", "ambivalent", "prevalent"]),
    ("ven", "come", "Latin", ["convene", "intervene", "revenue"]),
    ("ver", "truth", "Latin", ["verify", "veracity", "aver"]),
    ("vert", "turn", "Latin", ["convert", "avert", "revert"]),
    ("vid", "see", "Latin", ["evident", "provide", "video"]),
    ("viv", "live", "Latin", ["vivid", "revive", "vivacious"]),
    ("voc", "call, voice", "Latin", ["vocabulary", "advocate", "equivocate"]),
    ("vol", "wish, will", "Latin", ["voluntary", "malevolent", "benevolent"]),
]


def build_words():
    seen = set()
    out = []
    for w, d in WORDS_RAW:
        lw = w.lower()
        if lw in COMMON_BLOCKLIST:
            continue
        if lw in seen:
            continue
        seen.add(lw)
        pos = classify_pos(w)
        out.append((w, d, pos))
    for w, d, pos in REPLACEMENTS:
        lw = w.lower()
        if lw in seen:
            continue
        seen.add(lw)
        out.append((w, d, pos))
    return out


def main():
    words = build_words()
    words_payload = [
        {"id": str(i + 1), "word": w, "definition": d, "partOfSpeech": p}
        for i, (w, d, p) in enumerate(words)
    ]
    roots_payload = [
        {"id": str(i + 1), "root": r, "meaning": m, "origin": o, "examples": e}
        for i, (r, m, o, e) in enumerate(ROOTS)
    ]
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    path = os.path.join(root, "Studium", "Resources", "sat-vocab-flashcards.json")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump({"words": words_payload, "roots": roots_payload}, f, ensure_ascii=False, indent=2)
    counts = {}
    for _, _, p in words:
        counts[p] = counts.get(p, 0) + 1
    print(len(words), "words (POS counts:", counts, "),", len(ROOTS), "roots ->", path)


if __name__ == "__main__":
    main()
